name: Deploy Server
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      PORT: ${{secrets.PORT}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: $SERVER_HOST
          key: $SSH_PRIVATE_KEY
          port: 22
          script: |
            cd home/ubuntu/nest-app
            git pull
