name: Deploy Server
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      PORT: ${{secrets.PORT}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
      - name: creating ssh key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 400 ssh_key.pem
      - name: connecting to server
        run:
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST '
          cd /nest-app
          git pull
          sudo docker compose down
          sudo docker compose up --build -d
          '
